# Site settings
title: is Q
SEOTitle: is Q的博客 | is Q Blog
header-img: img/home-bg-ship.jpg
email: 1509525854@qq.com
description: "你听好了，趁着年轻什么都别管 | is Q，Node.js & Vue.js Developer "
keyword: "is Q, is Q博客, is Q Blog, 博客, 个人网站, 互联网, Web, JavaScript, 前端, Node.js"
url: "https://www.isqqy.com"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog' /isQ.github.io

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: true
weibo_username:     false
zhihu_username:     willking-7
github_username:    yang131323
# twitter_username:   isheng
#facebook_username:  huxpro
#linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN  



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



# Disqus settings
disqus_username: false

# Netease settings
netease_comment: false

# Gitalk
gitalk_clientID: 'e9bbe5cab49497965c55'
gitalk_clientSecret: '9275e5b23e992c045ea1b88cee2299fe5def3581'
gitalk_repo: 'mgblog-comment' # 评论仓库
gitalk_owner: 'yang131323' # 仓库拥有者
gitalk_admin: 'yang131323'



# Analytics settings
# Baidu Analytics 
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: 'UA-137551468-1'            # Format: UA-xxxxxx-xx
ga_domain: mapo.io



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "趁着年轻，做点事情"
sidebar-avatar: /img/avatar.png      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false

copyright: true



# Friends
friends: [
    {
        title: "Mapo",
        href: "https://mapo.io/"
    }
]
